apiVersion: v1
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImRIbHNaWEprWVhSaGRISnZianBFWVhSaGRISnZiakp3YjJsdWREQkViMk5yWlhJPSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0K
kind: Secret
metadata:
  name: regcred
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
